# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imię:')),
                ('surname', models.CharField(max_length=200, verbose_name='Nazwisko:')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł:')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Podtytuł:')),
                ('pub_year', models.IntegerField(max_length=5, verbose_name='Rok wydania:')),
                ('which_edition', models.CharField(blank=True, max_length=3, verbose_name='Które wydanie:')),
                ('pub_place', models.CharField(max_length=200, verbose_name='Miasto:')),
                ('pages', models.IntegerField(max_length=4, verbose_name='Ilość stron:')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='Autorzy:')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoverType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookCategory', verbose_name='Kategoria:'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.CoverType', verbose_name='Typ okładki:'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher', verbose_name='Wydawca/Wydawnictwo:'),
        ),
    ]
